### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by simonfrisch1** [TaddyLab/BDS#1]
Great book - got both the digital and print version!

Just a couple of typos I found:

1) fixed affects (vs. fixed effects) - Footnote 14, Chapter 5

2) In the code comments under semi-conductors there is a typo in the word deviance.

https://github.com/TaddyLab/BDS/blob/128b8ba1c034629e713199b451087599d867ad11/examples/semiconductor.R#L48

**Comment by mataddy** [comment]
@simonfrish1 you rule!!  Thanks for getting this started.  I've started the typos wiki at https://github.com/TaddyLab/BDS/wiki/Typos.  For code, if you can make the edit to semiconductor.R and do a pull request I'll update.
