### ISSUE TITLE
code update for R 4.0

### ISSUE THREAD

**Issue by laszlosandor** [TaddyLab/BDS#15]
Some of the example code in the repo (and the book) does not work on R 4.0.

Instead of a PR on fixes separately, maybe I can guide you to [my forked repo](https://github.com/laszlosandor/BDScourse/tree/master/examples) with Jupyter notebooks reproducing the examples chapter by chapter (with minimal comments, mostly reformatting the original repo's inline comments into cells with Markdown.)

**Comment by mataddy** [comment]
Thanks Laszlo (for this and the typos)!  I appreciate it.  Perhaps we could do a PR to replace the current notebooks with yours, or I just point to your repo in the readme?

**Comment by laszlosandor** [comment]
Thanks @mataddy , you should be able to link to the PR now and close this issue.

Needless to say, you are welcome to review the PR that the notebooks make sense (mostly the comments).

Thanks for everything!

**Comment by mataddy** [comment]
this is awesome, thanks laszlo!  I really appreciate it, this will be very useful for others.
