### ISSUE TITLE
Broken url

### ISSUE THREAD

**Issue by itamarcaspi** [TaddyLab/BDS#3]
Hi, 

The link to the book's datasets that appears in the Kindle edition (Introduction) is broken.

Now: [http://taddylab.com/BDS](http://taddylab.com/BDS)

Should be: [http://taddylab.com/bds.html](http://taddylab.com/bds.html)

(LOVE the book!)

**Comment by mataddy** [comment]
thanks for the heads up!  it should be fixed now (both links should work)
