### ISSUE TITLE
Typos eq: 1.10 and Marginal Likelihood

### ISSUE THREAD

**Issue by keblu** [TaddyLab/BDS#8]
Hi,

Bought the digital edition of your book and, while not too far into it as for right now, I enjoy it a lot. 

I noticed some typos in the Bayesian Inference subsection, specifically for equation 1.10 and the Marginal Likelihood equation.

Given the defintion of P(X|Θ) given as the probability of X given Θ

For equation 1.10, in the book (digital) we have:

     P(Θ|X) = P(Θ|X)π(Θ)/P(X) ∝ P(Θ|X)π(Θ)

I believe it should instead be:

     P(Θ|X) = P(X|Θ)π(Θ)/P(X) ∝ P(X|Θ)π(Θ)

Similarly, for the Marginal Likelihood equation:

     P(X) = ∫P(Θ|X)π(Θ)dΘ

I believe it should instead be:

     P(X) = ∫P(X|Θ)π(Θ)dΘ

**Comment by mataddy** [comment]
Gah!  Many thanks, that is embarrassing.  A Bayesian screws up bayes rule!  We’ll fix in the next printing.
